### ISSUE TITLE
Web App Rewriting: Roadmap

### ISSUE THREAD

**Issue by Arthi-chaud** [Arthi-chaud/Blee#112]
The Flutter Web app is slow af. Using it does not feel nice.
Since shipping a mobile app is not planned, there is no point in using Flutter anymore.

This issue is the roadmap to the rewriting of the webapp in VueJS + Nuxt

- Dockerisation
  - [x] Production Dockerfile
  - [x] Development Dockerfile
- Use previously defined environment variables
  - [x] API URL for Server-side fetches
  - [x] API URL for Client-side fetches
- Branding
  - [x] Use previously defined color theme
  - [x] Make Dark theme same a light theme
  - [x] Setup favicon
  - [x] Add Icon to navigation bar
- Player
  - [x] Display Thumbnail while video is loading
  - [x] Controls should appear on mouse move
  - [x] Controls should fade when mouse has not moved for 3 seconds
  - [x] If media is not compatible with the browser, transcode
  - Controls Layout
    - [x] Next to the scrollbar should be the current progress and the total duration
    - [x] The Scrollbar should have chapter indicators
    - [x] There should be the poster to the left side
    - [x] There should be the chapter's name, the movie's name / the extra's name 
    - [x] There should be the artist's name
- CI
  - The following actions should be implemented
  - [x] Build
  - [x] Lint
  - [x] Format
  - [x] Publish
    - [x] For now, it should be published under the name 'blee-front-vue'
- Pages
  - [x] Navigation Bar
  - [x] Bottom Navigation Bar
  - [x] Packages Page
  - [x] Artists Page
  - [x] Extras Page
  - [x] Artist Page
    - [x] Header
    - [x] Infinite Package List
    - [x] Infinite Extra List
  - [x] Package Page
    - [x] Header
    - [x] Infinite Movie List
    - [x] Infinite Chapter List
    - [x] Infinite Extra List
  - [x] Settings Page
